kmstore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import (
    show_main,
    create_keyboard,
    create_mouse,
    show_xml_keyboard,
    show_xml_mouse,
    show_json_keyboard,
    show_json_mouse,
    show_xml_by_id_keyboard,
    show_xml_by_id_mouse,
    show_json_by_id_keyboard,
    show_json_by_id_mouse,
    register,
    login_user,
    logout_user,
    show_json_by_author,
    delete_keyboard,
    delete_mouse,
    edit_keyboard,
    edit_mouse,
    create_keyboard_ajax,
    create_mouse_ajax,
    create_keyboard_api,
    create_mouse_api,
    show_products_by_author_id
)

app_name = "main"

urlpatterns = [
    path("", show_main, name="show_main"),
    path("create/keyboard/", create_keyboard, name="create_keyboard"),
    path("create/mouse/", create_mouse, name="create_mouse"),
    path("xml/keyboard/", show_xml_keyboard, name="show_xml_keyboard"),
    path("xml/mouse/", show_xml_mouse, name="show_xml_mouse"),
    path("json/keyboard/", show_json_keyboard, name="show_json_keyboard"),
    path("json/mouse/", show_json_mouse, name="show_json_mouse"),
    path(
        "xml/keyboard/<str:id>/",
        show_xml_by_id_keyboard,
        name="show_xml_by_id_keyboard",
    ),
    path("xml/mouse/<str:id>/", show_xml_by_id_mouse, name="show_xml_by_id_mouse"),
    path("json/keyboard/<str:id>/", show_json_by_id_keyboard, name="show_json_by_id_keyboard"),
    path("json/mouse/<str:id>/", show_json_by_id_mouse, name="show_json_by_id_mouse"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path("json/author/", show_json_by_author, name="show_json_by_author"),
    path("delete/keyboard/<str:id>/", delete_keyboard, name="delete_keyboard"),
    path("delete/mouse/<str:id>/", delete_mouse, name="delete_mouse"),
    path("edit/keyboard/<str:id>/", edit_keyboard, name="edit_keyboard"),
    path("edit/mouse/<str:id>/", edit_mouse, name="edit_mouse"),
    path("create-keyboard-ajax", create_keyboard_ajax, name="create_keyboard_ajax"),
    path("create-mouse-ajax", create_mouse_ajax, name="create_mouse_ajax"),
    path("create-keyboard/", create_keyboard_api, name="create_keyboard_api"),
    path("create-mouse/", create_mouse_api, name="create_mouse_api"),
    path("products/<str:id>/", show_products_by_author_id, name="show_products_by_author_id"),
]

main/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User


# Create your models here.
class Keyboard(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.TextField()
    stock = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    switch = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)
    image = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Mouse(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.TextField()
    stock = models.IntegerField()
    dpi = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    weight = models.IntegerField()
    brand = models.CharField(max_length=100)
    image = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

main/forms.py
from django.forms import ModelForm
from main.models import Keyboard, Mouse


class KeyboardForm(ModelForm):
    class Meta:
        model = Keyboard
        fields = ["name", "price", "stock", "switch", "brand", "image", "description"]
        labels = {
            "name": "Name",
            "price": "Price",
            "description": "Description",
            "stock": "Stock",
            "switch": "Switch",
            "brand": "Brand",
            "image": "Image",
        }

class MouseForm(ModelForm):
    class Meta:
        model = Mouse
        fields = ["name", "price", "stock", "dpi", "weight", "brand", "image", "description"]
        labels = {
            "name": "Name",
            "price": "Price",
            "description": "Description",
            "stock": "Stock",
            "dpi": "DPI",
            "weight": "Weight",
            "brand": "Brand",
            "image": "Image",
        }

main/views.py
import json
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from main.models import Keyboard, Mouse
from main.forms import KeyboardForm, MouseForm
from django.core import serializers
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.urls import reverse
from itertools import chain
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST


# Create your views here.
@login_required(login_url="/login")
def show_main(request):
    keyboard_mouse_all = list(chain(Keyboard.objects.all(), Mouse.objects.all()))
    context = {
        "title": "KMStore",
        "name": "Tristan Agra Yudhistira",
        "npm": "2306245112",
        "class": "PBP D",
        "current_user": request.user.username,
        "last_login": request.COOKIES["last_login"],
        "keyboard_mouse_all": keyboard_mouse_all,
    }

    return render(request, "main.html", context)


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your account has been successfully created!")
            return redirect("main:login")
    context = {"form": form}
    return render(request, "register.html", context)


def login_user(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie("last_login", str(datetime.datetime.now()))
            return response

    else:
        form = AuthenticationForm(request)
    context = {"form": form}
    return render(request, "login.html", context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse("main:login"))
    response.delete_cookie("last_login")
    return response


@login_required(login_url="/login")
def create_keyboard(request):
    form = KeyboardForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        keyboard = form.save(commit=False)
        keyboard.author = request.user
        keyboard.save()
        return redirect("main:show_main")

    return render(request, "keyboard_form.html", {"form": form})


@csrf_exempt
@require_POST
def create_keyboard_ajax(request):
    name = request.POST.get("name")
    price = request.POST.get("price")
    description = request.POST.get("description")
    stock = request.POST.get("stock")
    switch = request.POST.get("switch")
    brand = request.POST.get("brand")
    image = request.POST.get("image")
    author = request.user

    keyboard = Keyboard(
        name=name,
        price=price,
        description=description,
        stock=stock,
        switch=switch,
        brand=brand,
        image=image,
        author=author,
    )

    keyboard.save()

    return HttpResponse("Keyboard has been created successfully!", status=201)


@csrf_exempt
@require_POST
def create_mouse_ajax(request):
    name = request.POST.get("name")
    price = request.POST.get("price")
    description = request.POST.get("description")
    stock = request.POST.get("stock")
    dpi = request.POST.get("dpi")
    weight = request.POST.get("weight")
    brand = request.POST.get("brand")
    image = request.POST.get("image")
    author = request.user

    mouse = Mouse(
        name=name,
        price=price,
        description=description,
        stock=stock,
        dpi=dpi,
        weight=weight,
        brand=brand,
        image=image,
        author=author,
    )

    mouse.save()

    return HttpResponse("Mouse has been created successfully!", status=201)


@login_required(login_url="/login")
def create_mouse(request):
    form = MouseForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        mouse = form.save(commit=False)
        mouse.author = request.user
        mouse.save()
        return redirect("main:show_main")

    return render(request, "mouse_form.html", {"form": form})


def show_xml_keyboard(request):
    data = Keyboard.objects.all()
    return HttpResponse(
        serializers.serialize("xml", data), content_type="application/xml"
    )


def show_xml_mouse(request):
    data = Mouse.objects.all()
    return HttpResponse(
        serializers.serialize("xml", data), content_type="application/xml"
    )


def show_json_keyboard(request):
    data = Keyboard.objects.all()
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_json_mouse(request):
    data = Mouse.objects.all()
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_xml_by_id_keyboard(request, id):
    data = Keyboard.objects.filter(pk=id)
    return HttpResponse(
        serializers.serialize("xml", data), content_type="application/xml"
    )


def show_xml_by_id_mouse(request, id):
    data = Mouse.objects.filter(pk=id)
    return HttpResponse(
        serializers.serialize("xml", data), content_type="application/xml"
    )


def show_json_by_id_keyboard(request, id):
    data = Keyboard.objects.filter(pk=id)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_json_by_id_mouse(request, id):
    data = Mouse.objects.filter(pk=id)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_json_by_author(request):
    keyboard_listings = Keyboard.objects.filter(author=request.user)
    mouse_listings = Mouse.objects.filter(author=request.user)
    data = list(chain(keyboard_listings, mouse_listings))
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )

def show_products_by_author_id(request, id):
    keyboard_listings = Keyboard.objects.filter(author=id)
    mouse_listings = Mouse.objects.filter(author=id)
    data = list(chain(keyboard_listings, mouse_listings))
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )

@login_required(login_url="/login")
def delete_keyboard(request, id):
    keyboard = Keyboard.objects.get(pk=id)
    keyboard.delete()
    return redirect("main:show_main")


@login_required(login_url="/login")
def delete_mouse(request, id):
    mouse = Mouse.objects.get(pk=id)
    mouse.delete()
    return redirect("main:show_main")


def edit_keyboard(request, id):
    keyboard = Keyboard.objects.get(pk=id)
    form = KeyboardForm(request.POST or None, instance=keyboard)

    if form.is_valid() and request.method == "POST":
        keyboard = form.save(commit=False)
        keyboard.author = request.user
        keyboard.save()
        return redirect("main:show_main")

    return render(request, "keyboard_form.html", {"form": form})


def edit_mouse(request, id):
    mouse = Mouse.objects.get(pk=id)
    form = MouseForm(request.POST or None, instance=mouse)

    if form.is_valid() and request.method == "POST":
        mouse = form.save(commit=False)
        mouse.author = request.user
        mouse.save()
        return redirect("main:show_main")

    return render(request, "mouse_form.html", {"form": form})


@csrf_exempt
def create_keyboard_api(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            name = data["name"]
            price = int(data["price"])
            description = data["description"]
            stock = int(data["stock"])
            switch = data["switch"]
            brand = data["brand"]
            image = data["image"]
            author = request.user
            
            if price < 0:
                raise Exception("Price must be greater than 0.")
            
            if stock < 0:
                raise Exception("Stock must be greater than 0.")

            keyboard = Keyboard.objects.create(
                name=name,
                price=price,
                description=description,
                stock=stock,
                switch=switch,
                brand=brand,
                image=image,
                author=author,
            )

            if keyboard is None:
                raise Exception("Failed to create keyboard.")

            keyboard.save()

            return JsonResponse(
                {
                    "status": "success",
                    "message": "Keyboard has been created successfully!",
                },
                status=201,
            )
        except Exception as e:
            return JsonResponse(
                {
                    "status": "failed",
                    "message": str(e),
                },
                status=400,
            )
    else:
        return JsonResponse(
            {
                "status": False,
                "message": "Invalid request method.",
            },
            status=400,
        )


@csrf_exempt
def create_mouse_api(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            name = data["name"]
            price = int(data["price"])
            description = data["description"]
            stock = int(data["stock"])
            dpi = int(data["dpi"])
            weight = int(data["weight"])
            brand = data["brand"]
            image = data["image"]
            author = request.user

            if price < 0:
                raise Exception("Price must be greater than 0.")

            if stock < 0:

main/templates/card.html
<div
  class="p-4 rounded-lg flex flex-col gap-3 justify-center border border-gray-300 shadow-lg m-4 hover:opacity-80 transition-all"
>
  <img
    width="200px"
    src="{{ prod.image }}"
    class="mx-auto"
    alt="{{ prod.name }}"
  />
  <h2 class="text-xl font-bold text-center">{{ prod.name }}</h2>
  <p class="text-white">{{ prod.description }}</p>
  <div class="grid grid-cols-2">
    <h2 class="font-bold">Brand</h2>
    <p class="text-white">: {{ prod.brand }}</p>
    {% if prod.dpi %}
    <h2 class="font-bold">Category</h2>
    <p class="text-white">: Mouse</p>
    <h2 class="font-bold">DPI</h2>
    <p class="text-white">: {{ prod.dpi }}</p>
    {% endif %} {% if prod.switch %}
    <h2 class="font-bold">Category</h2>
    <p class="text-white">: Keyboard</p>
    <h2 class="font-bold">Switch</h2>
    <p class="text-white">: {{ prod.switch }}</p>
    {% endif %} {% if prod.weight %}
    <h2 class="font-bold">Weight</h2>
    <p class="text-white">: {{ prod.weight }}g</p>
    {% endif %}
    <h2 class="font-bold">Stock</h2>
    <p class="text-white">: {{ prod.stock }}</p>
    <h2 class="font-bold">Price</h2>
    <p class="text-white">: {{ prod.price }}</p>
    <h2 class="font-bold">Penjual</h2>
    <p class="text-white">: {{ prod.author.username }}</p>
  </div>
  <div>
    {% if prod.dpi %}
    <a href="{% url 'main:delete_mouse' prod.id %}">
      <button
        class="p-2 bg-red-500 hover:bg-red-700 text-[#0d0e0d] transition-all rounded-[12px] hover:shadow-lg text-white"
      >
        Delete
      </button>
    </a>
    <a href="{% url 'main:edit_mouse' prod.id %}">
      <button
        class="p-2 bg-[#904edb] hover:bg-[#632f77] active:bg-[#7d3699] text-[#0d0e0d] transition-all rounded-[12px] hover:shadow-lg text-white"
      >
        Edit
      </button>
    </a>
    {% endif %} {% if prod.switch %}
    <a href="{% url 'main:delete_keyboard' prod.id %}">
      <button
        class="p-2 bg-red-500 hover:bg-red-700 active:bg-[#7d3699] text-[#0d0e0d] transition-all rounded-[12px] hover:shadow-lg text-white"
      >
        Delete
      </button>
    </a>
    <a href="{% url 'main:edit_keyboard' prod.id %}">
      <button
        class="p-2 bg-[#904edb] hover:bg-[#632f77] active:bg-[#7d3699] text-[#0d0e0d] transition-all rounded-[12px] hover:shadow-lg text-white"
      >
        Edit
      </button>
    </a>
    {% endif %}
  </div>
</div>

main/templates/hero.html
{% load static %}
<section class="min-h-[90vh] flex items-center">
  <div class="flex lg:flex-row flex-col gap-4 items-center justify-between w-full px-[5vw] my-[5vh] lg:my-[15vh]">
    <div class="flex flex-col gap-2">
      <h1 class="text-white font-bold text-[40px]">
        Welcome to <span class="text-[#904edb] animate-pulse">KMStore</span>
        <br />Sell your
        <span class="bg-purple-500 px-2 rounded-lg animate-pulse">mouse</span>
        and
        <span class="bg-purple-500 px-2 rounded-lg animate-pulse"
          >keyboard</span
        >
        here!
      </h1>
      <div class='flex gap-2'>
      <a href="#product">
        <button
          class="bg-[#b33e95] hover:bg-[#832e6e] active:bg-[#fcd7f3] text-[#0d0e0d] font-semibold transition-all rounded-lg hover:shadow-lg p-2"
        >
          Check This Out
        </button>
      </a>
      <button data-modal-target="keyboardFormModal" data-modal-toggle="keyboardFormModal" class="btn bg-[#904edb] hover:bg-[#901eeb] text-[#0d0e0d] font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out hover:shadow-lg" onclick="showModal();">
        Add New Keyboard
      </button>
      </div>
    </div>
    <div class="grid grid-cols-2 max-md:grid-cols-1 gap-6">
      <div class='max-md:hidden'></div>
      <a
        href="{% url 'main:create_keyboard' %}"
        class="flex flex-col gap-4 items-center justify-center px-6 py-8 border border-gray-300 rounded-[16px] hover:opacity-80 hover:translate-y-8 transition-all"
      >
        <img
          src="{% static 'image/keyboard.png' %}"
          alt="Keyboard"
          class="w-[300px] h-[250px]"
        />
        <h2 class="text-white font-bold text-[16px]">Sell a Keyboard</h2>
      </a>
      <a
        href="{% url 'main:create_mouse' %}"
        class="flex flex-col gap-4 items-center justify-center px-6 py-8 border border-gray-300 rounded-[16px] hover:opacity-80 hover:-translate-y-8 transition-all"
      >
        <img
          src="{% static 'image/mouse.png' %}"
          alt="Mouse"
          class="w-[300px] h-[250px]"
        />
        <h2 class="text-white font-bold text-[16px]">Sell a Mouse</h2>
      </a>
      <div class='max-md:hidden'></div>
    </div>
  </div>
</section>

main/templates/keyboard_form.html
{% extends 'base.html' %} {% block meta %}
<title>KMStore | Add Keyboard</title>
{% endblock meta %} {% block content %}
<main class="flex items-center justify-center min-h-screen">
  <section
    class="bg-black bg-opacity-50 backdrop-filter backdrop-blur-lg p-4 rounded-[20px] shadow-lg flex flex-col gap-5 items-center justify-center"
  >
    <h1 class="font-bold text-[20px] md:text-[24px] text-center">
      Add New Keyboard to Sell
    </h1>

    <form method="POST" class="flex flex-col gap-5">
      {% csrf_token %}
      <div class="grid md:grid-cols-2 grid-cols-1 gap-2 md:gap-4">
        {% for field in form %}
        <div
          class="flex flex-col max-md:justify-center max-md:items-center gap-2 {% if field.name == 'description' %}md:col-span-2 items-center{% endif %}"
        >
          <label for="{{ field.id_for_label }}" class="text-white text-start"
            >{{ field.label }}</label
          >
          <div
            class="p-2 text-black bg-[#4625581a] hover:bg-[#3602010a] transition-all rounded-lg"
          >
            {{ field }}
          </div>
        </div>
        {% endfor %}
      </div>
      <button
        class="p-2 bg-[#904edb] hover:bg-[#632f77] active:bg-[#7d3699] text-[#0d0e0d] transition-all rounded-[12px] hover:shadow-lg text-white"
        type="submit"
        value="Add Keyboard"
      >
        Add Keyboard
      </button>
    </form>
  </section>
</main>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %} {% block meta %}
<title>KMStore | Login</title>
{% endblock meta %} {% block content %}
<main class="flex items-center justify-center min-h-screen">
  <section
    class="bg-black bg-opacity-50 backdrop-filter backdrop-blur-lg px-8 py-6 rounded-[20px] shadow-lg flex flex-col gap-5"
  >
    <h1 class="font-bold text-[24px] text-center">Login</h1>
    <form method="POST" action="" class="flex flex-col gap-5">
      {% csrf_token %}
      <div class="grid gap-4">
        <div class="flex flex-col gap-2">
          <label for="{{ form.username.id_for_label }}" class="text-white"
            >{{ form.username.label }}</label
          >
          <input
            class="p-2 text-gray-300 bg-[#4625581a] hover:bg-[#3602010a] transition-all rounded-lg"
            type="text"
            name="username"
            id="username"
            placeholder="Username anda"
            value="{{ form.username.value|default_if_none:'' }}"
          />
        </div>
        <div class="flex flex-col gap-2">
          <label for="password" class="text-white">Password</label>
          <input
            class="p-2 text-gray-300 bg-[#4625581a] hover:bg-[#3602010a] transition-all rounded-lg"
            type="password"
            name="password"
            id="password"
            placeholder="Password anda"
            value="{{ form.password.value|default_if_none:'' }}"
          />
        </div>
      </div>
      <button
        class="p-2 bg-[#904edb] hover:bg-[#632f77] active:bg-[#7d3699] text-[#0d0e0d] transition-all rounded-[12px] hover:shadow-lg text-white"
        type="submit"
        value="Login"
      >
        Login
      </button>
    </form>
    <p class="text-white">
      Don't have an account yet?
      <a
        href="{% url 'main:register' %}"
        class="text-[#904edb] hover:text-[#632f77] transition-all"
        >Register Now</a
      >
    </p>
  </section>
</main>
{% endblock content %}

main/templates/mouse_form.html
{% extends 'base.html' %} {% block meta %}
<title>KMStore | Add Mouse</title>
{% endblock meta %} {% block content %}
<main class="flex items-center justify-center min-h-screen">
  <section
    class="bg-black bg-opacity-50 backdrop-filter backdrop-blur-lg p-4 rounded-[20px] shadow-lg flex flex-col gap-5 items-center justify-center"
  >
    <h1 class="font-bold text-[24px]">Add New Mouse to Sell</h1>

    <form method="POST" class="flex flex-col gap-5">
      {% csrf_token %}
      <div class="grid grid-cols-2 gap-4">
        {% for field in form %}
        <div
          class="flex flex-col gap-2 {% if field.name == 'description' %}col-span-2 items-center{% endif %}"
        >
          <label for="{{ field.id_for_label }}" class="text-white"
            >{{ field.label }}</label
          >
          <div
            class="p-2 text-black bg-[#4625581a] hover:bg-[#3602010a] transition-all rounded-lg"
          >
            {{ field }}
          </div>
        </div>
        {% endfor %}
      </div>
      <button
        class="p-2 bg-[#904edb] hover:bg-[#632f77] active:bg-[#7d3699] text-[#0d0e0d] transition-all rounded-[12px] hover:shadow-lg text-white"
        type="submit"
        value="Add Mouse"
      >
        Add Mouse
      </button>
    </form>
  </section>
</main>

{% endblock %}

main/templates/navbar.html
<nav class="fixed w-full border-b-gray-800 border-b flex justify-between items-center py-6 px-8 backdrop-blur-lg">
  <a href="" class="text-[#904edb] font-bold text-2xl">KMStore</a>
  <ul class="flex gap-4">
    <li>
      <a href="/create/keyboard" class="text-[#904edb] hover:text-[#632f77] transition-all font-semibold">Keyboard</a>
    </li>
    <li>
      <a href="/create/mouse" class="text-[#904edb] hover:text-[#632f77] transition-all font-semibold">Mouse</a>
    </li>
    <li>
      <p class="text-[#904edb] hover:text-[#632f77] transition-all font-semibold">Welcome, {{ current_user }}</p>
    </li>
    <li>
      <a href="{% url 'main:logout' %}" class="text-red-600 hover:text-red-800 transition-all font-semibold">Logout</a>
    </li>
  </ul>
</nav>

main/templates/register.html
{% extends 'base.html' %} {% block meta %}
<title>KMStore | Register</title>
{% endblock meta %} {% block content %}
<main class="flex items-center justify-center min-h-screen">
  <section
    class="bg-black bg-opacity-50 backdrop-filter backdrop-blur-lg px-8 py-6 rounded-[20px] shadow-lg flex flex-col gap-5"
  >
    <h1 class="font-bold text-[24px] text-center">Register</h1>
    <form method="POST" class="flex flex-col gap-5">
      {% csrf_token %}
      <div class="grid gap-4">
        <div class="flex flex-col gap-2">
          <label for="{{ form.username.id_for_label }}" class="text-white"
            >{{ form.username.label }}</label
          >
          <input
            class="p-2 text-gray-300 bg-[#4625581a] hover:bg-[#3602010a] transition-all rounded-lg"
            type="text"
            name="username"
            id="username"
            placeholder="Username anda"
            value="{{ form.username.value|default_if_none:'' }}"
          />
        </div>
        <div class="flex flex-col gap-2">
          <label for="password1" class="text-white"
            >Password</label
          >
          <input
            class="p-2 text-gray-300 bg-[#4625581a] hover:bg-[#3602010a] transition-all rounded-lg"
            type="password"
            name="password1"
            id="password1"
            placeholder="Password anda"
            value="{{ form.password1.value|default_if_none:'' }}"
          />
        </div>
        <div class="flex flex-col gap-2">
          <label for="{{ form.password2.id_for_label }}" class="text-white"
            >{{ form.password2.label }}</label
          >
          <input
            class="p-2 text-gray-300 bg-[#4625581a] hover:bg-[#3602010a] transition-all rounded-lg"
            type="password"
            name="password2"
            id="password2"
            placeholder="Ulangi password anda"
            value="{{ form.password2.value|default_if_none:'' }}"
          />
        </div>
      </div>
      <button
        class="p-2 bg-[#904edb] hover:bg-[#632f77] active:bg-[#7d3699] text-[#0d0e0d] transition-all rounded-[12px] hover:shadow-lg text-white"
        type="submit"
        value="register"
      >
        Register
      </button>
    </form>
    <p class="text-white">
      Already have an account?
      <a
        href="{% url 'main:login' %}"
        class="text-[#904edb] hover:text-[#632f77] transition-all"
        >Login Now</a
      >
    </p>
  </section>
</main>
{% endblock content %}